"""add audio_url to scan

Revision ID: 6c715b719374
Revises: 47d36e520ac6
Create Date: 2026-04-19 17:38:38.625114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c715b719374'
down_revision: Union[str, Sequence[str], None] = '47d36e520ac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('audio_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'audio_url')
    # ### end Alembic commands ###
