# """initial migration

# Revision ID: a27a4d9a40ae
# Revises: 
# Create Date: 2026-03-31 19:07:55.151135

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision: str = 'a27a4d9a40ae'
# down_revision: Union[str, Sequence[str], None] = None
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_table('requirements')
#     op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
#     op.drop_table('notifications')
#     op.drop_index(op.f('ix_history_history_id'), table_name='history')
#     op.drop_index(op.f('ix_history_viewed_at'), table_name='history')
#     op.drop_table('history')
#     op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
#     op.drop_table('messages')
#     op.drop_index(op.f('ix_diseases_disease_id'), table_name='diseases')
#     op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
#     op.drop_index(op.f('ix_diseases_urgency_level'), table_name='diseases')
#     op.drop_table('diseases')
#     op.drop_index(op.f('ix_consultations_consult_id'), table_name='consultations')
#     op.drop_index(op.f('ix_consultations_created_at'), table_name='consultations')
#     op.drop_index(op.f('ix_consultations_updated_at'), table_name='consultations')
#     op.drop_table('consultations')
#     op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
#     op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
#     op.drop_table('scans')
#     op.drop_index(op.f('ix_treatments_treatment_id'), table_name='treatments')
#     op.drop_table('treatments')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table('treatments',
#     sa.Column('treatment_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('treatment_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
#     sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('application_method', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('treatments_disease_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('treatment_id', name=op.f('treatments_pkey'))
#     )
#     op.create_index(op.f('ix_treatments_treatment_id'), 'treatments', ['treatment_id'], unique=False)
#     op.create_table('scans',
#     sa.Column('scan_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('custom_label', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
#     sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('urgency_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('scans_disease_id_fkey'), ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('scans_user_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('scan_id', name=op.f('scans_pkey'))
#     )
#     op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
#     op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
#     op.create_table('consultations',
#     sa.Column('consult_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
#     sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['expert_id'], ['experts.expert_id'], name=op.f('consultations_expert_id_fkey'), ondelete='SET NULL'),
#     sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('consultations_scan_id_fkey'), ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('consultations_user_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('consult_id', name=op.f('consultations_pkey'))
#     )
#     op.create_index(op.f('ix_consultations_updated_at'), 'consultations', ['updated_at'], unique=False)
#     op.create_index(op.f('ix_consultations_created_at'), 'consultations', ['created_at'], unique=False)
#     op.create_index(op.f('ix_consultations_consult_id'), 'consultations', ['consult_id'], unique=False)
#     op.create_table('diseases',
#     sa.Column('disease_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
#     sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('symtoms', sa.TEXT(), autoincrement=False, nullable=False),
#     sa.Column('urgency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
#     sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('icon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
#     sa.Column('color_hex', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.PrimaryKeyConstraint('disease_id', name=op.f('diseases_pkey'))
#     )
#     op.create_index(op.f('ix_diseases_urgency_level'), 'diseases', ['urgency_level'], unique=False)
#     op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
#     op.create_index(op.f('ix_diseases_disease_id'), 'diseases', ['disease_id'], unique=False)
#     op.create_table('messages',
#     sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('consultation_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
#     sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
#     sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consult_id'], name=op.f('messages_consultation_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
#     )
#     op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
#     op.create_table('history',
#     sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
#     sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('history_scan_id_fkey'), ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('history_user_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('history_id', name=op.f('history_pkey'))
#     )
#     op.create_index(op.f('ix_history_viewed_at'), 'history', ['viewed_at'], unique=False)
#     op.create_index(op.f('ix_history_history_id'), 'history', ['history_id'], unique=False)
#     op.create_table('notifications',
#     sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
#     sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
#     sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], name=op.f('notifications_admin_id_fkey'), ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['expert_id'], ['experts.expert_id'], name=op.f('notifications_expert_id_fkey'), ondelete='CASCADE'),
#     sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
#     sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
#     )
#     op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
#     op.create_table('requirements',
#     sa.Column('requirement_id', sa.INTEGER(), autoincrement=True, nullable=False),
#     sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
#     sa.Column('requirement', sa.VARCHAR(), autoincrement=False, nullable=True),
#     sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
#     sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('requirements_disease_id_fkey')),
#     sa.PrimaryKeyConstraint('requirement_id', name=op.f('requirements_pkey'))
#     )
#     # ### end Alembic commands ###





"""initial migration

Revision ID: a27a4d9a40ae
Revises: 
Create Date: 2026-03-31 19:07:55.151135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27a4d9a40ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop in correct order — dependents first, then parents

    # requirements depends on diseases
    op.drop_table('requirements')

    # notifications (no dependencies)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')

    # history depends on scans and users
    op.drop_index(op.f('ix_history_history_id'), table_name='history')
    op.drop_index(op.f('ix_history_viewed_at'), table_name='history')
    op.drop_table('history')

    # messages depends on consultations
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_table('messages')

    # consultations depends on scans, users, experts
    op.drop_index(op.f('ix_consultations_consult_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_created_at'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_updated_at'), table_name='consultations')
    op.drop_table('consultations')

    # treatments depends on diseases
    op.drop_index(op.f('ix_treatments_treatment_id'), table_name='treatments')
    op.drop_table('treatments')

    # scans depends on diseases and users
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_index(op.f('ix_scans_scan_id'), table_name='scans')
    op.drop_table('scans')

    # diseases — now safe to drop since scans and treatments are gone
    op.drop_index(op.f('ix_diseases_disease_id'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_name'), table_name='diseases')
    op.drop_index(op.f('ix_diseases_urgency_level'), table_name='diseases')
    op.drop_table('diseases')


def downgrade() -> None:
    """Downgrade schema."""
    op.create_table('treatments',
    sa.Column('treatment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('treatment_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('dosage', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('duration', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('application_method', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('treatments_disease_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('treatment_id', name=op.f('treatments_pkey'))
    )
    op.create_index(op.f('ix_treatments_treatment_id'), 'treatments', ['treatment_id'], unique=False)
    op.create_table('scans',
    sa.Column('scan_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_label', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('urgency_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('scans_disease_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('scans_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id', name=op.f('scans_pkey'))
    )
    op.create_index(op.f('ix_scans_scan_id'), 'scans', ['scan_id'], unique=False)
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    op.create_table('consultations',
    sa.Column('consult_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.expert_id'], name=op.f('consultations_expert_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('consultations_scan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('consultations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consult_id', name=op.f('consultations_pkey'))
    )
    op.create_index(op.f('ix_consultations_updated_at'), 'consultations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_consultations_created_at'), 'consultations', ['created_at'], unique=False)
    op.create_index(op.f('ix_consultations_consult_id'), 'consultations', ['consult_id'], unique=False)
    op.create_table('diseases',
    sa.Column('disease_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('symtoms', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('urgency_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('icon_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color_hex', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('disease_id', name=op.f('diseases_pkey'))
    )
    op.create_index(op.f('ix_diseases_urgency_level'), 'diseases', ['urgency_level'], unique=False)
    op.create_index(op.f('ix_diseases_name'), 'diseases', ['name'], unique=True)
    op.create_index(op.f('ix_diseases_disease_id'), 'diseases', ['disease_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('consultation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.consult_id'], name=op.f('messages_consultation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_table('history',
    sa.Column('history_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.scan_id'], name=op.f('history_scan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', name=op.f('history_pkey'))
    )
    op.create_index(op.f('ix_history_viewed_at'), 'history', ['viewed_at'], unique=False)
    op.create_index(op.f('ix_history_history_id'), 'history', ['history_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], name=op.f('notifications_admin_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.expert_id'], name=op.f('notifications_expert_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('requirements',
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('disease_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.disease_id'], name=op.f('requirements_disease_id_fkey')),
    sa.PrimaryKeyConstraint('requirement_id', name=op.f('requirements_pkey'))
    )
