"""add mid_name to admin

Revision ID: f91e6e6fe19f
Revises: a27a4d9a40ae
Create Date: 2026-03-31 19:15:11.412302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f91e6e6fe19f'
down_revision: Union[str, Sequence[str], None] = 'a27a4d9a40ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
