from app.models.user import User
from app.models.disease import Disease
from app.models.scan import Scan
from app.models.treatment import Treatment
from app.models.disease_requirement import Requirement
from app.models.expert import Expert
from app.models.consult import Consultation
from app.models.message import Message
from app.models.notification import Notification
from app.models.history import History
from app.models.admin import Admin
